// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goospf.proto

package goospfapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnableRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableRequest) Reset()         { *m = EnableRequest{} }
func (m *EnableRequest) String() string { return proto.CompactTextString(m) }
func (*EnableRequest) ProtoMessage()    {}
func (*EnableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe8e30501ec2189, []int{0}
}

func (m *EnableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableRequest.Unmarshal(m, b)
}
func (m *EnableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableRequest.Marshal(b, m, deterministic)
}
func (m *EnableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableRequest.Merge(m, src)
}
func (m *EnableRequest) XXX_Size() int {
	return xxx_messageInfo_EnableRequest.Size(m)
}
func (m *EnableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableRequest proto.InternalMessageInfo

type EnableResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableResponse) Reset()         { *m = EnableResponse{} }
func (m *EnableResponse) String() string { return proto.CompactTextString(m) }
func (*EnableResponse) ProtoMessage()    {}
func (*EnableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe8e30501ec2189, []int{1}
}

func (m *EnableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableResponse.Unmarshal(m, b)
}
func (m *EnableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableResponse.Marshal(b, m, deterministic)
}
func (m *EnableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableResponse.Merge(m, src)
}
func (m *EnableResponse) XXX_Size() int {
	return xxx_messageInfo_EnableResponse.Size(m)
}
func (m *EnableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableResponse proto.InternalMessageInfo

func (m *EnableResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DisableRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableRequest) Reset()         { *m = DisableRequest{} }
func (m *DisableRequest) String() string { return proto.CompactTextString(m) }
func (*DisableRequest) ProtoMessage()    {}
func (*DisableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe8e30501ec2189, []int{2}
}

func (m *DisableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableRequest.Unmarshal(m, b)
}
func (m *DisableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableRequest.Marshal(b, m, deterministic)
}
func (m *DisableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableRequest.Merge(m, src)
}
func (m *DisableRequest) XXX_Size() int {
	return xxx_messageInfo_DisableRequest.Size(m)
}
func (m *DisableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableRequest proto.InternalMessageInfo

type DisableResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableResponse) Reset()         { *m = DisableResponse{} }
func (m *DisableResponse) String() string { return proto.CompactTextString(m) }
func (*DisableResponse) ProtoMessage()    {}
func (*DisableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe8e30501ec2189, []int{3}
}

func (m *DisableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableResponse.Unmarshal(m, b)
}
func (m *DisableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableResponse.Marshal(b, m, deterministic)
}
func (m *DisableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableResponse.Merge(m, src)
}
func (m *DisableResponse) XXX_Size() int {
	return xxx_messageInfo_DisableResponse.Size(m)
}
func (m *DisableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisableResponse proto.InternalMessageInfo

func (m *DisableResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*EnableRequest)(nil), "goospfapi.EnableRequest")
	proto.RegisterType((*EnableResponse)(nil), "goospfapi.EnableResponse")
	proto.RegisterType((*DisableRequest)(nil), "goospfapi.DisableRequest")
	proto.RegisterType((*DisableResponse)(nil), "goospfapi.DisableResponse")
}

func init() { proto.RegisterFile("goospf.proto", fileDescriptor_fbe8e30501ec2189) }

var fileDescriptor_fbe8e30501ec2189 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcf, 0xcf, 0x2f,
	0x2e, 0x48, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0xf0, 0x12, 0x0b, 0x32, 0x95,
	0xf8, 0xb9, 0x78, 0x5d, 0xf3, 0x12, 0x93, 0x72, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x94, 0x34, 0xb8, 0xf8, 0x60, 0x02, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x62, 0x5c, 0x6c,
	0x45, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x92,
	0x00, 0x17, 0x9f, 0x4b, 0x66, 0x31, 0xb2, 0x5e, 0x4d, 0x2e, 0x7e, 0xb8, 0x08, 0x7e, 0xcd, 0x46,
	0x3d, 0x8c, 0x5c, 0x9c, 0xee, 0x60, 0x57, 0x38, 0x16, 0x64, 0x0a, 0xd9, 0x72, 0xb1, 0x41, 0x2c,
	0x15, 0x92, 0xd0, 0x83, 0xbb, 0x4d, 0x0f, 0xc5, 0x61, 0x52, 0x92, 0x58, 0x64, 0xa0, 0x96, 0x38,
	0x70, 0xb1, 0x43, 0xed, 0x15, 0x42, 0x56, 0x85, 0xea, 0x3a, 0x29, 0x29, 0x6c, 0x52, 0x10, 0x13,
	0x92, 0xd8, 0xc0, 0x01, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x7a, 0xd5, 0xfc, 0x28,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoospfApiClient is the client API for GoospfApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoospfApiClient interface {
	Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error)
	Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*DisableResponse, error)
}

type goospfApiClient struct {
	cc *grpc.ClientConn
}

func NewGoospfApiClient(cc *grpc.ClientConn) GoospfApiClient {
	return &goospfApiClient{cc}
}

func (c *goospfApiClient) Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error) {
	out := new(EnableResponse)
	err := c.cc.Invoke(ctx, "/goospfapi.GoospfApi/Enable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goospfApiClient) Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*DisableResponse, error) {
	out := new(DisableResponse)
	err := c.cc.Invoke(ctx, "/goospfapi.GoospfApi/Disable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoospfApiServer is the server API for GoospfApi service.
type GoospfApiServer interface {
	Enable(context.Context, *EnableRequest) (*EnableResponse, error)
	Disable(context.Context, *DisableRequest) (*DisableResponse, error)
}

func RegisterGoospfApiServer(s *grpc.Server, srv GoospfApiServer) {
	s.RegisterService(&_GoospfApi_serviceDesc, srv)
}

func _GoospfApi_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoospfApiServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goospfapi.GoospfApi/Enable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoospfApiServer).Enable(ctx, req.(*EnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoospfApi_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoospfApiServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goospfapi.GoospfApi/Disable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoospfApiServer).Disable(ctx, req.(*DisableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoospfApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goospfapi.GoospfApi",
	HandlerType: (*GoospfApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enable",
			Handler:    _GoospfApi_Enable_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _GoospfApi_Disable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goospf.proto",
}
