// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goisis.proto

package goisisapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnableRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableRequest) Reset()         { *m = EnableRequest{} }
func (m *EnableRequest) String() string { return proto.CompactTextString(m) }
func (*EnableRequest) ProtoMessage()    {}
func (*EnableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{0}
}

func (m *EnableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableRequest.Unmarshal(m, b)
}
func (m *EnableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableRequest.Marshal(b, m, deterministic)
}
func (m *EnableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableRequest.Merge(m, src)
}
func (m *EnableRequest) XXX_Size() int {
	return xxx_messageInfo_EnableRequest.Size(m)
}
func (m *EnableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableRequest proto.InternalMessageInfo

type EnableResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableResponse) Reset()         { *m = EnableResponse{} }
func (m *EnableResponse) String() string { return proto.CompactTextString(m) }
func (*EnableResponse) ProtoMessage()    {}
func (*EnableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{1}
}

func (m *EnableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableResponse.Unmarshal(m, b)
}
func (m *EnableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableResponse.Marshal(b, m, deterministic)
}
func (m *EnableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableResponse.Merge(m, src)
}
func (m *EnableResponse) XXX_Size() int {
	return xxx_messageInfo_EnableResponse.Size(m)
}
func (m *EnableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableResponse proto.InternalMessageInfo

func (m *EnableResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DisableRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableRequest) Reset()         { *m = DisableRequest{} }
func (m *DisableRequest) String() string { return proto.CompactTextString(m) }
func (*DisableRequest) ProtoMessage()    {}
func (*DisableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{2}
}

func (m *DisableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableRequest.Unmarshal(m, b)
}
func (m *DisableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableRequest.Marshal(b, m, deterministic)
}
func (m *DisableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableRequest.Merge(m, src)
}
func (m *DisableRequest) XXX_Size() int {
	return xxx_messageInfo_DisableRequest.Size(m)
}
func (m *DisableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableRequest proto.InternalMessageInfo

type DisableResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableResponse) Reset()         { *m = DisableResponse{} }
func (m *DisableResponse) String() string { return proto.CompactTextString(m) }
func (*DisableResponse) ProtoMessage()    {}
func (*DisableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{3}
}

func (m *DisableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableResponse.Unmarshal(m, b)
}
func (m *DisableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableResponse.Marshal(b, m, deterministic)
}
func (m *DisableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableResponse.Merge(m, src)
}
func (m *DisableResponse) XXX_Size() int {
	return xxx_messageInfo_DisableResponse.Size(m)
}
func (m *DisableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisableResponse proto.InternalMessageInfo

func (m *DisableResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type InterfaceEnableRequest struct {
	Interface            string   `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceEnableRequest) Reset()         { *m = InterfaceEnableRequest{} }
func (m *InterfaceEnableRequest) String() string { return proto.CompactTextString(m) }
func (*InterfaceEnableRequest) ProtoMessage()    {}
func (*InterfaceEnableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{4}
}

func (m *InterfaceEnableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceEnableRequest.Unmarshal(m, b)
}
func (m *InterfaceEnableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceEnableRequest.Marshal(b, m, deterministic)
}
func (m *InterfaceEnableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceEnableRequest.Merge(m, src)
}
func (m *InterfaceEnableRequest) XXX_Size() int {
	return xxx_messageInfo_InterfaceEnableRequest.Size(m)
}
func (m *InterfaceEnableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceEnableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceEnableRequest proto.InternalMessageInfo

func (m *InterfaceEnableRequest) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

type InterfaceEnableResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceEnableResponse) Reset()         { *m = InterfaceEnableResponse{} }
func (m *InterfaceEnableResponse) String() string { return proto.CompactTextString(m) }
func (*InterfaceEnableResponse) ProtoMessage()    {}
func (*InterfaceEnableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{5}
}

func (m *InterfaceEnableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceEnableResponse.Unmarshal(m, b)
}
func (m *InterfaceEnableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceEnableResponse.Marshal(b, m, deterministic)
}
func (m *InterfaceEnableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceEnableResponse.Merge(m, src)
}
func (m *InterfaceEnableResponse) XXX_Size() int {
	return xxx_messageInfo_InterfaceEnableResponse.Size(m)
}
func (m *InterfaceEnableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceEnableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceEnableResponse proto.InternalMessageInfo

func (m *InterfaceEnableResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type InterfaceDisableRequest struct {
	Interface            string   `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceDisableRequest) Reset()         { *m = InterfaceDisableRequest{} }
func (m *InterfaceDisableRequest) String() string { return proto.CompactTextString(m) }
func (*InterfaceDisableRequest) ProtoMessage()    {}
func (*InterfaceDisableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{6}
}

func (m *InterfaceDisableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceDisableRequest.Unmarshal(m, b)
}
func (m *InterfaceDisableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceDisableRequest.Marshal(b, m, deterministic)
}
func (m *InterfaceDisableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceDisableRequest.Merge(m, src)
}
func (m *InterfaceDisableRequest) XXX_Size() int {
	return xxx_messageInfo_InterfaceDisableRequest.Size(m)
}
func (m *InterfaceDisableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceDisableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceDisableRequest proto.InternalMessageInfo

func (m *InterfaceDisableRequest) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

type InterfaceDisableResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceDisableResponse) Reset()         { *m = InterfaceDisableResponse{} }
func (m *InterfaceDisableResponse) String() string { return proto.CompactTextString(m) }
func (*InterfaceDisableResponse) ProtoMessage()    {}
func (*InterfaceDisableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{7}
}

func (m *InterfaceDisableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceDisableResponse.Unmarshal(m, b)
}
func (m *InterfaceDisableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceDisableResponse.Marshal(b, m, deterministic)
}
func (m *InterfaceDisableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceDisableResponse.Merge(m, src)
}
func (m *InterfaceDisableResponse) XXX_Size() int {
	return xxx_messageInfo_InterfaceDisableResponse.Size(m)
}
func (m *InterfaceDisableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceDisableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceDisableResponse proto.InternalMessageInfo

func (m *InterfaceDisableResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type AdjacencyGetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdjacencyGetRequest) Reset()         { *m = AdjacencyGetRequest{} }
func (m *AdjacencyGetRequest) String() string { return proto.CompactTextString(m) }
func (*AdjacencyGetRequest) ProtoMessage()    {}
func (*AdjacencyGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{8}
}

func (m *AdjacencyGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdjacencyGetRequest.Unmarshal(m, b)
}
func (m *AdjacencyGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdjacencyGetRequest.Marshal(b, m, deterministic)
}
func (m *AdjacencyGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdjacencyGetRequest.Merge(m, src)
}
func (m *AdjacencyGetRequest) XXX_Size() int {
	return xxx_messageInfo_AdjacencyGetRequest.Size(m)
}
func (m *AdjacencyGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdjacencyGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdjacencyGetRequest proto.InternalMessageInfo

type AdjacencyGetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdjacencyGetResponse) Reset()         { *m = AdjacencyGetResponse{} }
func (m *AdjacencyGetResponse) String() string { return proto.CompactTextString(m) }
func (*AdjacencyGetResponse) ProtoMessage()    {}
func (*AdjacencyGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{9}
}

func (m *AdjacencyGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdjacencyGetResponse.Unmarshal(m, b)
}
func (m *AdjacencyGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdjacencyGetResponse.Marshal(b, m, deterministic)
}
func (m *AdjacencyGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdjacencyGetResponse.Merge(m, src)
}
func (m *AdjacencyGetResponse) XXX_Size() int {
	return xxx_messageInfo_AdjacencyGetResponse.Size(m)
}
func (m *AdjacencyGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdjacencyGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdjacencyGetResponse proto.InternalMessageInfo

type AdjacencyMonitorRequest struct {
	Interface            string   `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdjacencyMonitorRequest) Reset()         { *m = AdjacencyMonitorRequest{} }
func (m *AdjacencyMonitorRequest) String() string { return proto.CompactTextString(m) }
func (*AdjacencyMonitorRequest) ProtoMessage()    {}
func (*AdjacencyMonitorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{10}
}

func (m *AdjacencyMonitorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdjacencyMonitorRequest.Unmarshal(m, b)
}
func (m *AdjacencyMonitorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdjacencyMonitorRequest.Marshal(b, m, deterministic)
}
func (m *AdjacencyMonitorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdjacencyMonitorRequest.Merge(m, src)
}
func (m *AdjacencyMonitorRequest) XXX_Size() int {
	return xxx_messageInfo_AdjacencyMonitorRequest.Size(m)
}
func (m *AdjacencyMonitorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdjacencyMonitorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdjacencyMonitorRequest proto.InternalMessageInfo

func (m *AdjacencyMonitorRequest) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

type AdjacencyMonitorResponse struct {
	Adjacency            []*Adjacency `protobuf:"bytes,1,rep,name=adjacency,proto3" json:"adjacency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AdjacencyMonitorResponse) Reset()         { *m = AdjacencyMonitorResponse{} }
func (m *AdjacencyMonitorResponse) String() string { return proto.CompactTextString(m) }
func (*AdjacencyMonitorResponse) ProtoMessage()    {}
func (*AdjacencyMonitorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{11}
}

func (m *AdjacencyMonitorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdjacencyMonitorResponse.Unmarshal(m, b)
}
func (m *AdjacencyMonitorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdjacencyMonitorResponse.Marshal(b, m, deterministic)
}
func (m *AdjacencyMonitorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdjacencyMonitorResponse.Merge(m, src)
}
func (m *AdjacencyMonitorResponse) XXX_Size() int {
	return xxx_messageInfo_AdjacencyMonitorResponse.Size(m)
}
func (m *AdjacencyMonitorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdjacencyMonitorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdjacencyMonitorResponse proto.InternalMessageInfo

func (m *AdjacencyMonitorResponse) GetAdjacency() []*Adjacency {
	if m != nil {
		return m.Adjacency
	}
	return nil
}

type DbLsGetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DbLsGetRequest) Reset()         { *m = DbLsGetRequest{} }
func (m *DbLsGetRequest) String() string { return proto.CompactTextString(m) }
func (*DbLsGetRequest) ProtoMessage()    {}
func (*DbLsGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{12}
}

func (m *DbLsGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbLsGetRequest.Unmarshal(m, b)
}
func (m *DbLsGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbLsGetRequest.Marshal(b, m, deterministic)
}
func (m *DbLsGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbLsGetRequest.Merge(m, src)
}
func (m *DbLsGetRequest) XXX_Size() int {
	return xxx_messageInfo_DbLsGetRequest.Size(m)
}
func (m *DbLsGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DbLsGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DbLsGetRequest proto.InternalMessageInfo

type DbLsGetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DbLsGetResponse) Reset()         { *m = DbLsGetResponse{} }
func (m *DbLsGetResponse) String() string { return proto.CompactTextString(m) }
func (*DbLsGetResponse) ProtoMessage()    {}
func (*DbLsGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{13}
}

func (m *DbLsGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbLsGetResponse.Unmarshal(m, b)
}
func (m *DbLsGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbLsGetResponse.Marshal(b, m, deterministic)
}
func (m *DbLsGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbLsGetResponse.Merge(m, src)
}
func (m *DbLsGetResponse) XXX_Size() int {
	return xxx_messageInfo_DbLsGetResponse.Size(m)
}
func (m *DbLsGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DbLsGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DbLsGetResponse proto.InternalMessageInfo

type DbLsMonitorRequest struct {
	Level                string   `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DbLsMonitorRequest) Reset()         { *m = DbLsMonitorRequest{} }
func (m *DbLsMonitorRequest) String() string { return proto.CompactTextString(m) }
func (*DbLsMonitorRequest) ProtoMessage()    {}
func (*DbLsMonitorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{14}
}

func (m *DbLsMonitorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbLsMonitorRequest.Unmarshal(m, b)
}
func (m *DbLsMonitorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbLsMonitorRequest.Marshal(b, m, deterministic)
}
func (m *DbLsMonitorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbLsMonitorRequest.Merge(m, src)
}
func (m *DbLsMonitorRequest) XXX_Size() int {
	return xxx_messageInfo_DbLsMonitorRequest.Size(m)
}
func (m *DbLsMonitorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DbLsMonitorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DbLsMonitorRequest proto.InternalMessageInfo

func (m *DbLsMonitorRequest) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

type DbLsMonitorResponse struct {
	Lsp                  []*Lsp   `protobuf:"bytes,1,rep,name=lsp,proto3" json:"lsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DbLsMonitorResponse) Reset()         { *m = DbLsMonitorResponse{} }
func (m *DbLsMonitorResponse) String() string { return proto.CompactTextString(m) }
func (*DbLsMonitorResponse) ProtoMessage()    {}
func (*DbLsMonitorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{15}
}

func (m *DbLsMonitorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbLsMonitorResponse.Unmarshal(m, b)
}
func (m *DbLsMonitorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbLsMonitorResponse.Marshal(b, m, deterministic)
}
func (m *DbLsMonitorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbLsMonitorResponse.Merge(m, src)
}
func (m *DbLsMonitorResponse) XXX_Size() int {
	return xxx_messageInfo_DbLsMonitorResponse.Size(m)
}
func (m *DbLsMonitorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DbLsMonitorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DbLsMonitorResponse proto.InternalMessageInfo

func (m *DbLsMonitorResponse) GetLsp() []*Lsp {
	if m != nil {
		return m.Lsp
	}
	return nil
}

type Adjacency struct {
	Interface                 string   `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	NeighborType              string   `protobuf:"bytes,2,opt,name=neighbor_type,json=neighborType,proto3" json:"neighbor_type,omitempty"`
	NeighborSysid             string   `protobuf:"bytes,3,opt,name=neighbor_sysid,json=neighborSysid,proto3" json:"neighbor_sysid,omitempty"`
	NeighborExtendedCircuitId uint32   `protobuf:"varint,4,opt,name=neighbor_extended_circuit_id,json=neighborExtendedCircuitId,proto3" json:"neighbor_extended_circuit_id,omitempty"`
	NeighborSnpa              string   `protobuf:"bytes,5,opt,name=neighbor_snpa,json=neighborSnpa,proto3" json:"neighbor_snpa,omitempty"`
	Usage                     string   `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	HoldTimer                 uint32   `protobuf:"varint,7,opt,name=hold_timer,json=holdTimer,proto3" json:"hold_timer,omitempty"`
	NeighborPriority          uint32   `protobuf:"varint,8,opt,name=neighbor_priority,json=neighborPriority,proto3" json:"neighbor_priority,omitempty"`
	Lastuptime                uint32   `protobuf:"varint,9,opt,name=lastuptime,proto3" json:"lastuptime,omitempty"`
	State                     string   `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *Adjacency) Reset()         { *m = Adjacency{} }
func (m *Adjacency) String() string { return proto.CompactTextString(m) }
func (*Adjacency) ProtoMessage()    {}
func (*Adjacency) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{16}
}

func (m *Adjacency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Adjacency.Unmarshal(m, b)
}
func (m *Adjacency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Adjacency.Marshal(b, m, deterministic)
}
func (m *Adjacency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Adjacency.Merge(m, src)
}
func (m *Adjacency) XXX_Size() int {
	return xxx_messageInfo_Adjacency.Size(m)
}
func (m *Adjacency) XXX_DiscardUnknown() {
	xxx_messageInfo_Adjacency.DiscardUnknown(m)
}

var xxx_messageInfo_Adjacency proto.InternalMessageInfo

func (m *Adjacency) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *Adjacency) GetNeighborType() string {
	if m != nil {
		return m.NeighborType
	}
	return ""
}

func (m *Adjacency) GetNeighborSysid() string {
	if m != nil {
		return m.NeighborSysid
	}
	return ""
}

func (m *Adjacency) GetNeighborExtendedCircuitId() uint32 {
	if m != nil {
		return m.NeighborExtendedCircuitId
	}
	return 0
}

func (m *Adjacency) GetNeighborSnpa() string {
	if m != nil {
		return m.NeighborSnpa
	}
	return ""
}

func (m *Adjacency) GetUsage() string {
	if m != nil {
		return m.Usage
	}
	return ""
}

func (m *Adjacency) GetHoldTimer() uint32 {
	if m != nil {
		return m.HoldTimer
	}
	return 0
}

func (m *Adjacency) GetNeighborPriority() uint32 {
	if m != nil {
		return m.NeighborPriority
	}
	return 0
}

func (m *Adjacency) GetLastuptime() uint32 {
	if m != nil {
		return m.Lastuptime
	}
	return 0
}

func (m *Adjacency) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type Lsp struct {
	Level                string                `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	DecodedCompleted     bool                  `protobuf:"varint,2,opt,name=decoded_completed,json=decodedCompleted,proto3" json:"decoded_completed,omitempty"`
	RawData              string                `protobuf:"bytes,3,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	LspId                string                `protobuf:"bytes,4,opt,name=lsp_id,json=lspId,proto3" json:"lsp_id,omitempty"`
	Checksum             uint32                `protobuf:"varint,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	RemainingLifetime    uint32                `protobuf:"varint,6,opt,name=remaining_lifetime,json=remainingLifetime,proto3" json:"remaining_lifetime,omitempty"`
	Sequence             uint32                `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Attributes           uint32                `protobuf:"varint,8,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Ipv4Addresses        []string              `protobuf:"bytes,9,rep,name=ipv4_addresses,json=ipv4Addresses,proto3" json:"ipv4_addresses,omitempty"`
	Ipv6Addresses        []string              `protobuf:"bytes,10,rep,name=ipv6_addresses,json=ipv6Addresses,proto3" json:"ipv6_addresses,omitempty"`
	Ipv4TeRouterid       string                `protobuf:"bytes,11,opt,name=ipv4_te_routerid,json=ipv4TeRouterid,proto3" json:"ipv4_te_routerid,omitempty"`
	Ipv6TeRouterid       string                `protobuf:"bytes,12,opt,name=ipv6_te_routerid,json=ipv6TeRouterid,proto3" json:"ipv6_te_routerid,omitempty"`
	ProtocolSupported    []uint32              `protobuf:"varint,13,rep,packed,name=protocol_supported,json=protocolSupported,proto3" json:"protocol_supported,omitempty"`
	DynamicHostname      string                `protobuf:"bytes,14,opt,name=dynamic_hostname,json=dynamicHostname,proto3" json:"dynamic_hostname,omitempty"`
	Authentication       *Authentication       `protobuf:"bytes,15,opt,name=authentication,proto3" json:"authentication,omitempty"`
	MtEntries            *MtEntries            `protobuf:"bytes,16,opt,name=mt_entries,json=mtEntries,proto3" json:"mt_entries,omitempty"`
	RouterCapabilities   []*RouterCapabilities `protobuf:"bytes,17,rep,name=router_capabilities,json=routerCapabilities,proto3" json:"router_capabilities,omitempty"`
	NodeTags             *NodeTags             `protobuf:"bytes,18,opt,name=node_tags,json=nodeTags,proto3" json:"node_tags,omitempty"`
	Binary               []byte                `protobuf:"bytes,19,opt,name=binary,proto3" json:"binary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Lsp) Reset()         { *m = Lsp{} }
func (m *Lsp) String() string { return proto.CompactTextString(m) }
func (*Lsp) ProtoMessage()    {}
func (*Lsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{17}
}

func (m *Lsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lsp.Unmarshal(m, b)
}
func (m *Lsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lsp.Marshal(b, m, deterministic)
}
func (m *Lsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lsp.Merge(m, src)
}
func (m *Lsp) XXX_Size() int {
	return xxx_messageInfo_Lsp.Size(m)
}
func (m *Lsp) XXX_DiscardUnknown() {
	xxx_messageInfo_Lsp.DiscardUnknown(m)
}

var xxx_messageInfo_Lsp proto.InternalMessageInfo

func (m *Lsp) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Lsp) GetDecodedCompleted() bool {
	if m != nil {
		return m.DecodedCompleted
	}
	return false
}

func (m *Lsp) GetRawData() string {
	if m != nil {
		return m.RawData
	}
	return ""
}

func (m *Lsp) GetLspId() string {
	if m != nil {
		return m.LspId
	}
	return ""
}

func (m *Lsp) GetChecksum() uint32 {
	if m != nil {
		return m.Checksum
	}
	return 0
}

func (m *Lsp) GetRemainingLifetime() uint32 {
	if m != nil {
		return m.RemainingLifetime
	}
	return 0
}

func (m *Lsp) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Lsp) GetAttributes() uint32 {
	if m != nil {
		return m.Attributes
	}
	return 0
}

func (m *Lsp) GetIpv4Addresses() []string {
	if m != nil {
		return m.Ipv4Addresses
	}
	return nil
}

func (m *Lsp) GetIpv6Addresses() []string {
	if m != nil {
		return m.Ipv6Addresses
	}
	return nil
}

func (m *Lsp) GetIpv4TeRouterid() string {
	if m != nil {
		return m.Ipv4TeRouterid
	}
	return ""
}

func (m *Lsp) GetIpv6TeRouterid() string {
	if m != nil {
		return m.Ipv6TeRouterid
	}
	return ""
}

func (m *Lsp) GetProtocolSupported() []uint32 {
	if m != nil {
		return m.ProtocolSupported
	}
	return nil
}

func (m *Lsp) GetDynamicHostname() string {
	if m != nil {
		return m.DynamicHostname
	}
	return ""
}

func (m *Lsp) GetAuthentication() *Authentication {
	if m != nil {
		return m.Authentication
	}
	return nil
}

func (m *Lsp) GetMtEntries() *MtEntries {
	if m != nil {
		return m.MtEntries
	}
	return nil
}

func (m *Lsp) GetRouterCapabilities() []*RouterCapabilities {
	if m != nil {
		return m.RouterCapabilities
	}
	return nil
}

func (m *Lsp) GetNodeTags() *NodeTags {
	if m != nil {
		return m.NodeTags
	}
	return nil
}

func (m *Lsp) GetBinary() []byte {
	if m != nil {
		return m.Binary
	}
	return nil
}

type Authentication struct {
	AuthenticationType   string   `protobuf:"bytes,1,opt,name=authentication_type,json=authenticationType,proto3" json:"authentication_type,omitempty"`
	AuthenticationKey    string   `protobuf:"bytes,2,opt,name=authentication_key,json=authenticationKey,proto3" json:"authentication_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Authentication) Reset()         { *m = Authentication{} }
func (m *Authentication) String() string { return proto.CompactTextString(m) }
func (*Authentication) ProtoMessage()    {}
func (*Authentication) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{18}
}

func (m *Authentication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authentication.Unmarshal(m, b)
}
func (m *Authentication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authentication.Marshal(b, m, deterministic)
}
func (m *Authentication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authentication.Merge(m, src)
}
func (m *Authentication) XXX_Size() int {
	return xxx_messageInfo_Authentication.Size(m)
}
func (m *Authentication) XXX_DiscardUnknown() {
	xxx_messageInfo_Authentication.DiscardUnknown(m)
}

var xxx_messageInfo_Authentication proto.InternalMessageInfo

func (m *Authentication) GetAuthenticationType() string {
	if m != nil {
		return m.AuthenticationType
	}
	return ""
}

func (m *Authentication) GetAuthenticationKey() string {
	if m != nil {
		return m.AuthenticationKey
	}
	return ""
}

type Topology struct {
	MtId                 uint32   `protobuf:"varint,1,opt,name=mt_id,json=mtId,proto3" json:"mt_id,omitempty"`
	Attributes           uint32   `protobuf:"varint,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topology) Reset()         { *m = Topology{} }
func (m *Topology) String() string { return proto.CompactTextString(m) }
func (*Topology) ProtoMessage()    {}
func (*Topology) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{19}
}

func (m *Topology) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topology.Unmarshal(m, b)
}
func (m *Topology) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topology.Marshal(b, m, deterministic)
}
func (m *Topology) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topology.Merge(m, src)
}
func (m *Topology) XXX_Size() int {
	return xxx_messageInfo_Topology.Size(m)
}
func (m *Topology) XXX_DiscardUnknown() {
	xxx_messageInfo_Topology.DiscardUnknown(m)
}

var xxx_messageInfo_Topology proto.InternalMessageInfo

func (m *Topology) GetMtId() uint32 {
	if m != nil {
		return m.MtId
	}
	return 0
}

func (m *Topology) GetAttributes() uint32 {
	if m != nil {
		return m.Attributes
	}
	return 0
}

type MtEntries struct {
	Topology             []*Topology `protobuf:"bytes,1,rep,name=topology,proto3" json:"topology,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MtEntries) Reset()         { *m = MtEntries{} }
func (m *MtEntries) String() string { return proto.CompactTextString(m) }
func (*MtEntries) ProtoMessage()    {}
func (*MtEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{20}
}

func (m *MtEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MtEntries.Unmarshal(m, b)
}
func (m *MtEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MtEntries.Marshal(b, m, deterministic)
}
func (m *MtEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MtEntries.Merge(m, src)
}
func (m *MtEntries) XXX_Size() int {
	return xxx_messageInfo_MtEntries.Size(m)
}
func (m *MtEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_MtEntries.DiscardUnknown(m)
}

var xxx_messageInfo_MtEntries proto.InternalMessageInfo

func (m *MtEntries) GetTopology() []*Topology {
	if m != nil {
		return m.Topology
	}
	return nil
}

type RouterCapabilities struct {
	Flags                uint32   `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouterCapabilities) Reset()         { *m = RouterCapabilities{} }
func (m *RouterCapabilities) String() string { return proto.CompactTextString(m) }
func (*RouterCapabilities) ProtoMessage()    {}
func (*RouterCapabilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{21}
}

func (m *RouterCapabilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouterCapabilities.Unmarshal(m, b)
}
func (m *RouterCapabilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouterCapabilities.Marshal(b, m, deterministic)
}
func (m *RouterCapabilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouterCapabilities.Merge(m, src)
}
func (m *RouterCapabilities) XXX_Size() int {
	return xxx_messageInfo_RouterCapabilities.Size(m)
}
func (m *RouterCapabilities) XXX_DiscardUnknown() {
	xxx_messageInfo_RouterCapabilities.DiscardUnknown(m)
}

var xxx_messageInfo_RouterCapabilities proto.InternalMessageInfo

func (m *RouterCapabilities) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

type NodeTags struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeTags) Reset()         { *m = NodeTags{} }
func (m *NodeTags) String() string { return proto.CompactTextString(m) }
func (*NodeTags) ProtoMessage()    {}
func (*NodeTags) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{22}
}

func (m *NodeTags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeTags.Unmarshal(m, b)
}
func (m *NodeTags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeTags.Marshal(b, m, deterministic)
}
func (m *NodeTags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeTags.Merge(m, src)
}
func (m *NodeTags) XXX_Size() int {
	return xxx_messageInfo_NodeTags.Size(m)
}
func (m *NodeTags) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeTags.DiscardUnknown(m)
}

var xxx_messageInfo_NodeTags proto.InternalMessageInfo

type Global struct {
	SystemId             string   `protobuf:"bytes,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Global) Reset()         { *m = Global{} }
func (m *Global) String() string { return proto.CompactTextString(m) }
func (*Global) ProtoMessage()    {}
func (*Global) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ca5a18eb6d27f6, []int{23}
}

func (m *Global) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Global.Unmarshal(m, b)
}
func (m *Global) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Global.Marshal(b, m, deterministic)
}
func (m *Global) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Global.Merge(m, src)
}
func (m *Global) XXX_Size() int {
	return xxx_messageInfo_Global.Size(m)
}
func (m *Global) XXX_DiscardUnknown() {
	xxx_messageInfo_Global.DiscardUnknown(m)
}

var xxx_messageInfo_Global proto.InternalMessageInfo

func (m *Global) GetSystemId() string {
	if m != nil {
		return m.SystemId
	}
	return ""
}

func init() {
	proto.RegisterType((*EnableRequest)(nil), "goisisapi.EnableRequest")
	proto.RegisterType((*EnableResponse)(nil), "goisisapi.EnableResponse")
	proto.RegisterType((*DisableRequest)(nil), "goisisapi.DisableRequest")
	proto.RegisterType((*DisableResponse)(nil), "goisisapi.DisableResponse")
	proto.RegisterType((*InterfaceEnableRequest)(nil), "goisisapi.InterfaceEnableRequest")
	proto.RegisterType((*InterfaceEnableResponse)(nil), "goisisapi.InterfaceEnableResponse")
	proto.RegisterType((*InterfaceDisableRequest)(nil), "goisisapi.InterfaceDisableRequest")
	proto.RegisterType((*InterfaceDisableResponse)(nil), "goisisapi.InterfaceDisableResponse")
	proto.RegisterType((*AdjacencyGetRequest)(nil), "goisisapi.AdjacencyGetRequest")
	proto.RegisterType((*AdjacencyGetResponse)(nil), "goisisapi.AdjacencyGetResponse")
	proto.RegisterType((*AdjacencyMonitorRequest)(nil), "goisisapi.AdjacencyMonitorRequest")
	proto.RegisterType((*AdjacencyMonitorResponse)(nil), "goisisapi.AdjacencyMonitorResponse")
	proto.RegisterType((*DbLsGetRequest)(nil), "goisisapi.DbLsGetRequest")
	proto.RegisterType((*DbLsGetResponse)(nil), "goisisapi.DbLsGetResponse")
	proto.RegisterType((*DbLsMonitorRequest)(nil), "goisisapi.DbLsMonitorRequest")
	proto.RegisterType((*DbLsMonitorResponse)(nil), "goisisapi.DbLsMonitorResponse")
	proto.RegisterType((*Adjacency)(nil), "goisisapi.Adjacency")
	proto.RegisterType((*Lsp)(nil), "goisisapi.Lsp")
	proto.RegisterType((*Authentication)(nil), "goisisapi.Authentication")
	proto.RegisterType((*Topology)(nil), "goisisapi.Topology")
	proto.RegisterType((*MtEntries)(nil), "goisisapi.MtEntries")
	proto.RegisterType((*RouterCapabilities)(nil), "goisisapi.RouterCapabilities")
	proto.RegisterType((*NodeTags)(nil), "goisisapi.NodeTags")
	proto.RegisterType((*Global)(nil), "goisisapi.Global")
}

func init() { proto.RegisterFile("goisis.proto", fileDescriptor_07ca5a18eb6d27f6) }

var fileDescriptor_07ca5a18eb6d27f6 = []byte{
	// 1086 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x51, 0x6f, 0xdb, 0x36,
	0x10, 0x86, 0xeb, 0xc6, 0xb1, 0x2e, 0x89, 0xed, 0xd0, 0x69, 0xa6, 0x78, 0x4d, 0xe6, 0xa9, 0x28,
	0xe0, 0x6e, 0x48, 0xda, 0xa5, 0x43, 0xfa, 0xb2, 0xa1, 0x0b, 0xd2, 0x20, 0x0b, 0x96, 0x66, 0x83,
	0x92, 0x87, 0x01, 0xc3, 0x20, 0xd0, 0xd2, 0xc5, 0xe1, 0x2a, 0x8b, 0x9c, 0x48, 0xb7, 0xd3, 0x0f,
	0xd8, 0xf3, 0x7e, 0xec, 0xfe, 0xc0, 0x40, 0x8a, 0x52, 0x24, 0xc7, 0x49, 0xf6, 0x66, 0x7e, 0xf7,
	0xdd, 0xf1, 0xd3, 0x47, 0xfa, 0x78, 0xb0, 0x3a, 0xe1, 0x4c, 0x32, 0xb9, 0x27, 0x52, 0xae, 0x38,
	0x71, 0xf2, 0x15, 0x15, 0xcc, 0xeb, 0xc2, 0xda, 0x71, 0x42, 0xc7, 0x31, 0xfa, 0xf8, 0xe7, 0x0c,
	0xa5, 0xf2, 0x46, 0xd0, 0x29, 0x00, 0x29, 0x78, 0x22, 0x91, 0x6c, 0x42, 0x2b, 0x45, 0x39, 0x8b,
	0x95, 0xdb, 0x18, 0x36, 0x46, 0x8e, 0x6f, 0x57, 0x5e, 0x0f, 0x3a, 0xef, 0x98, 0xac, 0xe6, 0xbe,
	0x80, 0x6e, 0x89, 0x3c, 0x90, 0x7c, 0x00, 0x9b, 0xa7, 0x89, 0xc2, 0xf4, 0x8a, 0x86, 0x58, 0x13,
	0x40, 0x9e, 0x82, 0xc3, 0x8a, 0x88, 0x4d, 0xba, 0x01, 0xbc, 0x6f, 0xe0, 0xb3, 0x5b, 0x79, 0x0f,
	0x6c, 0xf5, 0xa6, 0x92, 0x52, 0x17, 0xfc, 0xc0, 0x5e, 0xfb, 0xe0, 0xde, 0x4e, 0x7c, 0x60, 0xb3,
	0x27, 0xd0, 0x3f, 0x8c, 0xfe, 0xa0, 0x21, 0x26, 0x61, 0x76, 0x82, 0xaa, 0x70, 0x66, 0x13, 0x36,
	0xea, 0x70, 0x5e, 0x46, 0x6b, 0x2b, 0xf1, 0xf7, 0x3c, 0x61, 0x8a, 0xa7, 0xff, 0x4f, 0xdb, 0x39,
	0xb8, 0xb7, 0x13, 0xad, 0xb6, 0x7d, 0x70, 0x68, 0x11, 0x73, 0x1b, 0xc3, 0xe6, 0x68, 0x65, 0x7f,
	0x63, 0xaf, 0x3c, 0xf2, 0xbd, 0x32, 0xcf, 0xbf, 0xa1, 0x99, 0xc3, 0x1c, 0x9f, 0xc9, 0x8a, 0xe4,
	0x75, 0xe8, 0x96, 0x88, 0x55, 0xfb, 0x15, 0x10, 0x0d, 0xcd, 0x09, 0xdd, 0x80, 0xa5, 0x18, 0x3f,
	0x62, 0x6c, 0x45, 0xe6, 0x0b, 0xef, 0x0d, 0xf4, 0x6b, 0x5c, 0xab, 0x6d, 0x08, 0xcd, 0x58, 0x0a,
	0xab, 0xaa, 0x53, 0x51, 0x75, 0x26, 0x85, 0xaf, 0x43, 0xde, 0xbf, 0x8f, 0xc0, 0x29, 0x25, 0xde,
	0xef, 0x02, 0x79, 0x06, 0x6b, 0x09, 0xb2, 0xc9, 0xf5, 0x98, 0xa7, 0x81, 0xca, 0x04, 0xba, 0x8f,
	0x0c, 0x63, 0xb5, 0x00, 0x2f, 0x33, 0x81, 0xe4, 0x39, 0x74, 0x4a, 0x92, 0xcc, 0x24, 0x8b, 0xdc,
	0xa6, 0x61, 0x95, 0xa9, 0x17, 0x1a, 0x24, 0x6f, 0xe1, 0x69, 0x49, 0xc3, 0xbf, 0x14, 0x26, 0x11,
	0x46, 0x41, 0xc8, 0xd2, 0x70, 0xc6, 0x54, 0xc0, 0x22, 0xf7, 0xf1, 0xb0, 0x31, 0x5a, 0xf3, 0xb7,
	0x0a, 0xce, 0xb1, 0xa5, 0x1c, 0xe5, 0x8c, 0xd3, 0xa8, 0x26, 0x46, 0x26, 0x82, 0xba, 0x4b, 0x75,
	0x31, 0x17, 0x89, 0xa0, 0xda, 0xac, 0x99, 0xa4, 0x13, 0x74, 0x5b, 0xb9, 0x59, 0x66, 0x41, 0xb6,
	0x01, 0xae, 0x79, 0x1c, 0x05, 0x8a, 0x4d, 0x31, 0x75, 0x97, 0xcd, 0x4e, 0x8e, 0x46, 0x2e, 0x35,
	0x40, 0xbe, 0x86, 0xf5, 0xb2, 0xb2, 0x48, 0x19, 0x4f, 0x99, 0xca, 0xdc, 0xb6, 0x61, 0xf5, 0x8a,
	0xc0, 0x2f, 0x16, 0x27, 0x3b, 0x00, 0x31, 0x95, 0x6a, 0x26, 0x74, 0x31, 0xd7, 0x31, 0xac, 0x0a,
	0xa2, 0x15, 0x48, 0x45, 0x15, 0xba, 0x90, 0x2b, 0x30, 0x0b, 0xef, 0x9f, 0x16, 0x34, 0xcf, 0xa4,
	0x58, 0x7c, 0x98, 0x5a, 0x40, 0x84, 0x21, 0x37, 0x8e, 0xf0, 0xa9, 0x88, 0x51, 0x61, 0x64, 0xbc,
	0x6e, 0xfb, 0x3d, 0x1b, 0x38, 0x2a, 0x70, 0xb2, 0x05, 0xed, 0x94, 0x7e, 0x0a, 0x22, 0xaa, 0xa8,
	0x75, 0x7a, 0x39, 0xa5, 0x9f, 0xde, 0x51, 0x45, 0xc9, 0x13, 0x68, 0xc5, 0x52, 0x14, 0x6e, 0xea,
	0xf2, 0x52, 0x9c, 0x46, 0x64, 0x00, 0xed, 0xf0, 0x1a, 0xc3, 0x0f, 0x72, 0x36, 0x35, 0xa6, 0xad,
	0xf9, 0xe5, 0x9a, 0xec, 0x02, 0x49, 0x71, 0x4a, 0x59, 0xc2, 0x92, 0x49, 0x10, 0xb3, 0x2b, 0x34,
	0x9f, 0xd5, 0x32, 0xac, 0xf5, 0x32, 0x72, 0x66, 0x03, 0xba, 0x94, 0xd4, 0xf7, 0x32, 0x09, 0xd1,
	0xfa, 0x58, 0xae, 0xb5, 0x33, 0x54, 0xa9, 0x94, 0x8d, 0x67, 0x0a, 0xa5, 0xf5, 0xaf, 0x82, 0xe8,
	0x8b, 0xc2, 0xc4, 0xc7, 0x6f, 0x03, 0x1a, 0x45, 0x29, 0x4a, 0x89, 0xd2, 0x75, 0x86, 0x4d, 0x7d,
	0x51, 0x34, 0x7a, 0x58, 0x80, 0x96, 0x76, 0x50, 0xa1, 0x41, 0x49, 0x3b, 0xb8, 0xa1, 0x8d, 0xa0,
	0x67, 0xaa, 0x29, 0x0c, 0x52, 0x3e, 0x53, 0x98, 0xb2, 0xc8, 0x5d, 0x31, 0x5f, 0x6d, 0x76, 0xb9,
	0x44, 0xdf, 0xa2, 0x96, 0x79, 0x50, 0x63, 0xae, 0x96, 0xcc, 0x83, 0x0a, 0x73, 0x17, 0x88, 0xe9,
	0xe0, 0x21, 0x8f, 0x03, 0x39, 0x13, 0x82, 0xa7, 0xfa, 0x20, 0xd6, 0x86, 0x4d, 0x6d, 0x46, 0x11,
	0xb9, 0x28, 0x02, 0xe4, 0x05, 0xf4, 0xa2, 0x2c, 0xa1, 0x53, 0x16, 0x06, 0xd7, 0x5c, 0xaa, 0x84,
	0x4e, 0xd1, 0xed, 0x98, 0xc2, 0x5d, 0x8b, 0xff, 0x68, 0x61, 0x72, 0x08, 0x1d, 0x3a, 0x53, 0xd7,
	0x98, 0x28, 0x16, 0x52, 0xc5, 0x78, 0xe2, 0x76, 0x87, 0x8d, 0xd1, 0xca, 0xfe, 0x56, 0xb5, 0x71,
	0xd4, 0x08, 0xfe, 0x5c, 0x02, 0x79, 0x0d, 0x30, 0x55, 0x01, 0x26, 0x2a, 0x65, 0x28, 0xdd, 0x9e,
	0x49, 0xaf, 0xf6, 0x9d, 0xf7, 0xea, 0x38, 0x8f, 0xf9, 0xce, 0xb4, 0xf8, 0x49, 0xce, 0xa1, 0x9f,
	0x7f, 0x73, 0x10, 0x52, 0x41, 0xc7, 0x2c, 0x66, 0x4a, 0x67, 0xaf, 0x9b, 0xfe, 0xb0, 0x5d, 0xc9,
	0xce, 0x3d, 0x38, 0xaa, 0x90, 0x7c, 0x92, 0xde, 0xc2, 0xc8, 0x2b, 0x70, 0x12, 0x1e, 0x61, 0xa0,
	0xe8, 0x44, 0xba, 0xc4, 0x68, 0xe8, 0x57, 0xaa, 0x9c, 0xf3, 0x08, 0x2f, 0xe9, 0x44, 0xfa, 0xed,
	0xc4, 0xfe, 0xd2, 0x9d, 0x7c, 0xcc, 0x12, 0x9a, 0x66, 0x6e, 0x7f, 0xd8, 0x18, 0xad, 0xfa, 0x76,
	0xe5, 0x09, 0xe8, 0xd4, 0x3f, 0x98, 0xbc, 0x84, 0x7e, 0xfd, 0x93, 0xf3, 0x9e, 0x93, 0xff, 0x53,
	0x48, 0x3d, 0x64, 0x3a, 0xcf, 0x2e, 0xcc, 0xa1, 0xc1, 0x07, 0xcc, 0x6c, 0x8f, 0x5a, 0xaf, 0x47,
	0x7e, 0xc2, 0xcc, 0x7b, 0x0b, 0xed, 0x4b, 0x2e, 0x78, 0xcc, 0x27, 0x19, 0xe9, 0xc3, 0xd2, 0xd4,
	0xb4, 0x9d, 0x86, 0xb9, 0xa6, 0x8f, 0xa7, 0xba, 0xc3, 0xd4, 0x2f, 0xf0, 0xa3, 0xf9, 0x0b, 0xec,
	0x7d, 0x07, 0x4e, 0x69, 0x32, 0x79, 0x09, 0x6d, 0x65, 0xab, 0xd9, 0x76, 0x5b, 0x35, 0xa2, 0xd8,
	0xc8, 0x2f, 0x49, 0xba, 0xbb, 0xdf, 0x36, 0x59, 0x37, 0x84, 0xab, 0x58, 0x9b, 0x99, 0x0b, 0xc9,
	0x17, 0x1e, 0x40, 0xbb, 0xb0, 0xd2, 0x7b, 0x0e, 0xad, 0x93, 0x98, 0x8f, 0x69, 0x4c, 0x3e, 0x07,
	0x47, 0x66, 0x52, 0xe1, 0xb4, 0x10, 0xee, 0xf8, 0xed, 0x1c, 0x38, 0x8d, 0xf6, 0xff, 0x5e, 0x02,
	0xe7, 0xc4, 0xec, 0x7f, 0x28, 0x18, 0xf9, 0x1e, 0x5a, 0xf9, 0xf3, 0x4d, 0xdc, 0x8a, 0xaa, 0xda,
	0x24, 0x30, 0xd8, 0x5a, 0x10, 0xb1, 0xcf, 0xc8, 0x0f, 0xb0, 0x6c, 0x5f, 0x64, 0x52, 0x65, 0xd5,
	0x9f, 0xf7, 0xc1, 0x60, 0x51, 0xc8, 0x56, 0xf8, 0x15, 0xba, 0x73, 0x83, 0x04, 0xf9, 0xb2, 0x42,
	0x5f, 0x3c, 0x9c, 0x0c, 0xbc, 0xfb, 0x28, 0xb6, 0xf2, 0x6f, 0xd0, 0x9b, 0x1f, 0x1b, 0xc8, 0xc2,
	0xbc, 0x39, 0xb5, 0xcf, 0xee, 0xe5, 0xd8, 0xe2, 0x3f, 0xc3, 0x6a, 0x75, 0x90, 0x20, 0x3b, 0x8b,
	0x1e, 0xf6, 0x9b, 0x57, 0x7c, 0xf0, 0xc5, 0x9d, 0x71, 0x5b, 0xf0, 0x77, 0xe8, 0xcd, 0x0f, 0x12,
	0x35, 0xb5, 0x77, 0x8c, 0x27, 0x35, 0xb5, 0x77, 0x4d, 0x22, 0xaf, 0x1a, 0xe6, 0xa0, 0xf2, 0x29,
	0xa2, 0x7e, 0x50, 0xb5, 0x59, 0xa3, 0x7e, 0x50, 0xf5, 0xa1, 0x83, 0x9c, 0xc3, 0x4a, 0x65, 0x90,
	0x20, 0xdb, 0x73, 0xd4, 0x39, 0x59, 0x3b, 0x77, 0x85, 0x0b, 0x45, 0xe3, 0x96, 0xe9, 0x93, 0xaf,
	0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x05, 0x97, 0xc6, 0x13, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoisisApiClient is the client API for GoisisApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoisisApiClient interface {
	Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error)
	Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*DisableResponse, error)
	InterfaceEnable(ctx context.Context, in *InterfaceEnableRequest, opts ...grpc.CallOption) (*InterfaceEnableResponse, error)
	InterfaceDisable(ctx context.Context, in *InterfaceDisableRequest, opts ...grpc.CallOption) (*InterfaceDisableResponse, error)
	AdjacencyGet(ctx context.Context, in *AdjacencyGetRequest, opts ...grpc.CallOption) (*AdjacencyGetResponse, error)
	AdjacencyMonitor(ctx context.Context, in *AdjacencyMonitorRequest, opts ...grpc.CallOption) (GoisisApi_AdjacencyMonitorClient, error)
	DbLsGet(ctx context.Context, in *DbLsGetRequest, opts ...grpc.CallOption) (*DbLsGetResponse, error)
	DbLsMonitor(ctx context.Context, in *DbLsMonitorRequest, opts ...grpc.CallOption) (GoisisApi_DbLsMonitorClient, error)
}

type goisisApiClient struct {
	cc *grpc.ClientConn
}

func NewGoisisApiClient(cc *grpc.ClientConn) GoisisApiClient {
	return &goisisApiClient{cc}
}

func (c *goisisApiClient) Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error) {
	out := new(EnableResponse)
	err := c.cc.Invoke(ctx, "/goisisapi.GoisisApi/Enable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goisisApiClient) Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*DisableResponse, error) {
	out := new(DisableResponse)
	err := c.cc.Invoke(ctx, "/goisisapi.GoisisApi/Disable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goisisApiClient) InterfaceEnable(ctx context.Context, in *InterfaceEnableRequest, opts ...grpc.CallOption) (*InterfaceEnableResponse, error) {
	out := new(InterfaceEnableResponse)
	err := c.cc.Invoke(ctx, "/goisisapi.GoisisApi/InterfaceEnable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goisisApiClient) InterfaceDisable(ctx context.Context, in *InterfaceDisableRequest, opts ...grpc.CallOption) (*InterfaceDisableResponse, error) {
	out := new(InterfaceDisableResponse)
	err := c.cc.Invoke(ctx, "/goisisapi.GoisisApi/InterfaceDisable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goisisApiClient) AdjacencyGet(ctx context.Context, in *AdjacencyGetRequest, opts ...grpc.CallOption) (*AdjacencyGetResponse, error) {
	out := new(AdjacencyGetResponse)
	err := c.cc.Invoke(ctx, "/goisisapi.GoisisApi/AdjacencyGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goisisApiClient) AdjacencyMonitor(ctx context.Context, in *AdjacencyMonitorRequest, opts ...grpc.CallOption) (GoisisApi_AdjacencyMonitorClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GoisisApi_serviceDesc.Streams[0], "/goisisapi.GoisisApi/AdjacencyMonitor", opts...)
	if err != nil {
		return nil, err
	}
	x := &goisisApiAdjacencyMonitorClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoisisApi_AdjacencyMonitorClient interface {
	Recv() (*AdjacencyMonitorResponse, error)
	grpc.ClientStream
}

type goisisApiAdjacencyMonitorClient struct {
	grpc.ClientStream
}

func (x *goisisApiAdjacencyMonitorClient) Recv() (*AdjacencyMonitorResponse, error) {
	m := new(AdjacencyMonitorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *goisisApiClient) DbLsGet(ctx context.Context, in *DbLsGetRequest, opts ...grpc.CallOption) (*DbLsGetResponse, error) {
	out := new(DbLsGetResponse)
	err := c.cc.Invoke(ctx, "/goisisapi.GoisisApi/DbLsGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goisisApiClient) DbLsMonitor(ctx context.Context, in *DbLsMonitorRequest, opts ...grpc.CallOption) (GoisisApi_DbLsMonitorClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GoisisApi_serviceDesc.Streams[1], "/goisisapi.GoisisApi/DbLsMonitor", opts...)
	if err != nil {
		return nil, err
	}
	x := &goisisApiDbLsMonitorClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoisisApi_DbLsMonitorClient interface {
	Recv() (*DbLsMonitorResponse, error)
	grpc.ClientStream
}

type goisisApiDbLsMonitorClient struct {
	grpc.ClientStream
}

func (x *goisisApiDbLsMonitorClient) Recv() (*DbLsMonitorResponse, error) {
	m := new(DbLsMonitorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GoisisApiServer is the server API for GoisisApi service.
type GoisisApiServer interface {
	Enable(context.Context, *EnableRequest) (*EnableResponse, error)
	Disable(context.Context, *DisableRequest) (*DisableResponse, error)
	InterfaceEnable(context.Context, *InterfaceEnableRequest) (*InterfaceEnableResponse, error)
	InterfaceDisable(context.Context, *InterfaceDisableRequest) (*InterfaceDisableResponse, error)
	AdjacencyGet(context.Context, *AdjacencyGetRequest) (*AdjacencyGetResponse, error)
	AdjacencyMonitor(*AdjacencyMonitorRequest, GoisisApi_AdjacencyMonitorServer) error
	DbLsGet(context.Context, *DbLsGetRequest) (*DbLsGetResponse, error)
	DbLsMonitor(*DbLsMonitorRequest, GoisisApi_DbLsMonitorServer) error
}

func RegisterGoisisApiServer(s *grpc.Server, srv GoisisApiServer) {
	s.RegisterService(&_GoisisApi_serviceDesc, srv)
}

func _GoisisApi_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoisisApiServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goisisapi.GoisisApi/Enable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoisisApiServer).Enable(ctx, req.(*EnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoisisApi_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoisisApiServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goisisapi.GoisisApi/Disable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoisisApiServer).Disable(ctx, req.(*DisableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoisisApi_InterfaceEnable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceEnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoisisApiServer).InterfaceEnable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goisisapi.GoisisApi/InterfaceEnable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoisisApiServer).InterfaceEnable(ctx, req.(*InterfaceEnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoisisApi_InterfaceDisable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceDisableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoisisApiServer).InterfaceDisable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goisisapi.GoisisApi/InterfaceDisable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoisisApiServer).InterfaceDisable(ctx, req.(*InterfaceDisableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoisisApi_AdjacencyGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjacencyGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoisisApiServer).AdjacencyGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goisisapi.GoisisApi/AdjacencyGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoisisApiServer).AdjacencyGet(ctx, req.(*AdjacencyGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoisisApi_AdjacencyMonitor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AdjacencyMonitorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoisisApiServer).AdjacencyMonitor(m, &goisisApiAdjacencyMonitorServer{stream})
}

type GoisisApi_AdjacencyMonitorServer interface {
	Send(*AdjacencyMonitorResponse) error
	grpc.ServerStream
}

type goisisApiAdjacencyMonitorServer struct {
	grpc.ServerStream
}

func (x *goisisApiAdjacencyMonitorServer) Send(m *AdjacencyMonitorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GoisisApi_DbLsGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DbLsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoisisApiServer).DbLsGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goisisapi.GoisisApi/DbLsGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoisisApiServer).DbLsGet(ctx, req.(*DbLsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoisisApi_DbLsMonitor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DbLsMonitorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoisisApiServer).DbLsMonitor(m, &goisisApiDbLsMonitorServer{stream})
}

type GoisisApi_DbLsMonitorServer interface {
	Send(*DbLsMonitorResponse) error
	grpc.ServerStream
}

type goisisApiDbLsMonitorServer struct {
	grpc.ServerStream
}

func (x *goisisApiDbLsMonitorServer) Send(m *DbLsMonitorResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _GoisisApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goisisapi.GoisisApi",
	HandlerType: (*GoisisApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enable",
			Handler:    _GoisisApi_Enable_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _GoisisApi_Disable_Handler,
		},
		{
			MethodName: "InterfaceEnable",
			Handler:    _GoisisApi_InterfaceEnable_Handler,
		},
		{
			MethodName: "InterfaceDisable",
			Handler:    _GoisisApi_InterfaceDisable_Handler,
		},
		{
			MethodName: "AdjacencyGet",
			Handler:    _GoisisApi_AdjacencyGet_Handler,
		},
		{
			MethodName: "DbLsGet",
			Handler:    _GoisisApi_DbLsGet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AdjacencyMonitor",
			Handler:       _GoisisApi_AdjacencyMonitor_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DbLsMonitor",
			Handler:       _GoisisApi_DbLsMonitor_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goisis.proto",
}
